


using System.Reflection;
// This code automatically generated by a template. Do not edit it directly.

// Version information for an assembly consists of the following four values:
//      Major Version
//      Minor Version
//      Build Number
//      Revision (Year (2 digit) + Days since start of year)
[assembly: AssemblyInformationalVersion("0.2" +
#if DEBUG
    " DEBUG")]
#else
    "")]
#endif
